version-template: '$VERSION.$NEXT_PATCH_VERSION'
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: Breaking Changes 🛠
    labels:
      - breaking-change
  - title: 'New Features 🎉'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes 🛠'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '👒 Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
exclude-labels:
  - 'ignore-for-release'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '*.yml'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
template: |
  ## Changes

  $CHANGES