site_name: Home Assistant Fuel Prices
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
site_url: https://pantherale0.github.io/ha-fuelprices
plugins:
  - search
  - awesome-pages