# Find Fuel Locations service
find_fuel_station:
  fields:
    location:
      required: true
      selector:
        location:
          radius: true
    source:
      required: false
      selector:
        text:
          multiline: false
find_fuels:
  fields:
    location:
      required: true
      selector:
        location:
          radius: true
    type:
      required: true
      selector:
        text:
          multiline: false
    source:
      required: false
      selector:
        text:
          multiline: false
