site_name: Home Assistant Fuel Prices
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
site_url: https://fuelprices.ha.system32.uk
plugins:
  - search
  - awesome-pages