name: Create release

on:
  workflow_dispatch:
  push:
    tags: "*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: cho0o0/calver-release-action@2022.12.14.1
        with:
          generate_release_notes: true
          dry_run: true
          # Do not use GITHUB_TOKEN if you want to trigger other workflows
          timezone: "utc"
          api_token: ${{secrets.GITHUB_TOKEN}}
          release_title: "${version}"
